### ISSUE TITLE
Only one instance of colored text showing in sidebar where multiple instances appear in the document.

### ISSUE THREAD

**Issue by fcherman** [scarsu/NotionX#13]
And the instance that appeared in the sidebar wasn't even the first on the page.

![image](https://user-images.githubusercontent.com/59314/124662959-50dec180-de5e-11eb-9418-bfa467e3b68f.png)

On a slightly different note, it would be nice if the sidebar included any colored text that appeared in one of the properties fields (this happened to be a page from a database).

**Comment by scarsu** [comment]
Fixed in commit#4277bbf

**Comment by five-five0909** [comment]
可以出一个桌面端的版本吗
