### ISSUE TITLE
Shrink the List view when turning on Prevent Table Overflow

### ISSUE THREAD

**Issue by davidnvq** [scarsu/NotionX#15]
With the available version on Chrome Web store, I got the following "feature"  which shrinks the List view when turning on Prevent Table Overflow:
![image](https://user-images.githubusercontent.com/30741785/129974078-4af63bc7-8775-4faa-8e2c-47c80af93c65.png)

How can I fix this issue? Many thanks.

**Comment by scarsu** [comment]
Thank you for your feedback.It's a bug, and will be fixed on next version.
