### ISSUE TITLE
Ideas Collection | 意见收集帖🧠

### ISSUE THREAD

**Issue by scarsu** [scarsu/NotionX#2]
All suggestions for improving the Notion experience are welcome!
欢迎提出你在使用Notion过程中的痛点，本项目开发者会抓住一切提升Notion使用体验的机会~

**Comment by scarsu** [comment]
下一版本的部分计划，点击插件弹出popup面板中，整合一些快捷操作：
 
- [ ] 官方暗黑模式按钮
- [ ] 页面紧凑模式：full width+small text
- [ ] 隐藏页面评论
- [ ] 快捷键cheat sheet 速查

**Comment by lencx** [comment]
可以在项目设置中开启讨论区，收集想法，比用issues好很多，例如[vsgh discussions](https://github.com/lencx/vsgh/discussions)
开启方式：`Repo > Setting > Options > Discussions`

**Comment by scarsu** [comment]
> 可以在项目设置中开启讨论区，收集想法，比用issues好很多，例如[vsgh discussions](https://github.com/lencx/vsgh/discussions)
> 开启方式：`Repo > Setting > Options > Discussions`

好嘞

**Comment by scarsu** [comment]
此贴已经关闭，请移步 → https://github.com/scarsu/NotionX/discussions/4

This issue was closed，feedback → https://github.com/scarsu/NotionX/discussions/4
