### ISSUE TITLE
有时候notion排版图片和实际摘抄的网页图片尺寸相差太大

### ISSUE THREAD

**Issue by wlioi** [scarsu/NotionX#6]
有没有什么办法自动排版呀

**Comment by scarsu** [comment]
取决于摘抄网页的工具在转存图片时对尺寸的控制，对于NotionX来说，没有能力在转存后的notion页面中，获取图片在原始网页的尺寸

**Comment by wlioi** [comment]
好像不是这样的，因为用剪贴板也会把图标大小的图片变成很模糊的占据一半页宽的图片



---原始邮件---
发件人: "ScarSu"<notifications@github.com&gt;
发送时间: 2021年1月19日(周二) 上午8:42
收件人: "scarsu/NotionX"<NotionX@noreply.github.com&gt;;
抄送: "wlioi"<wlioi@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [scarsu/NotionX] 有时候notion排版图片和实际摘抄的网页图片尺寸相差太大 (#6)




 
取决于摘抄网页的工具在转存图片时对尺寸的控制，对于NotionX来说，没有能力在转存后的notion页面中，获取图片在原始网页的尺寸

**Comment by wlioi** [comment]
@scarsu 另外我的浏览器上这个插件好像不生效https://raw.githubusercontent.com/wlioi/2/main/Snipaste_2021-01-20_10-10-48.png

**Comment by scarsu** [comment]
> @scarsu 另外我的浏览器上这个插件好像不生效https://raw.githubusercontent.com/wlioi/2/main/Snipaste_2021-01-20_10-10-48.png

请参考这里
![image](https://user-images.githubusercontent.com/19526406/105118489-80487e80-5b09-11eb-80be-0ff57ebe51f1.png)

**Comment by scarsu** [comment]
> 好像不是这样的，因为用剪贴板也会把图标大小的图片变成很模糊的占据一半页宽的图片

我这复现 剪贴板粘贴图片后尺寸和原始图片的尺寸是一致的，你可以确认一下你复制图片时看到的尺寸是否是图片原始尺寸

**Comment by wlioi** [comment]
https://www.notion.so/wlioi/t-d4181f02affa4b9f9774b90b1807052b
你看，分别用chrome和火狐都复制了一些，好像没有区别

**Comment by wlioi** [comment]
https://www.notion.so/wlioi/t-d4181f02affa4b9f9774b90b1807052b
你看，分别用chrome和火狐都复制了一些，好像没有区别

> 
> 
> > 好像不是这样的，因为用剪贴板也会把图标大小的图片变成很模糊的占据一半页宽的图片
> 
> 我这复现 剪贴板粘贴图片后尺寸和原始图片的尺寸是一致的，你可以确认一下你复制图片时看到的尺寸是否是图片原始尺寸

**Comment by scarsu** [comment]
> https://www.notion.so/wlioi/t-d4181f02affa4b9f9774b90b1807052b
> 你看，分别用chrome和火狐都复制了一些，好像没有区别

![image](https://user-images.githubusercontent.com/19526406/105119919-357c3600-5b0c-11eb-9a1c-94e13ea4e575.png)
复制正常

**Comment by scarsu** [comment]
@wlioi  请注意tu'pian'yuan's图片原始尺寸
![image](https://user-images.githubusercontent.com/19526406/105120030-6eb4a600-5b0c-11eb-8d5e-1e9e70f853db.png)

**Comment by wlioi** [comment]
> 
> 
> @wlioi 请注意图片原始尺寸
> ![image](https://user-images.githubusercontent.com/19526406/105120030-6eb4a600-5b0c-11eb-8d5e-1e9e70f853db.png)

难道是我的系统问题，你可以查看我在这个文档的截图所有图片尺寸都是一样的

**Comment by wlioi** [comment]
或者我们讨论中，你说的是图片文件尺寸，我说的是实际显示尺寸

**Comment by wlioi** [comment]
@scarsu 
难道是我的系统问题，你可以查看我在这个文档的截图所有图片尺寸都是一样的
或者我们讨论中，你说的是图片文件尺寸，我说的是实际显示尺寸

**Comment by scarsu** [comment]
> 或者我们讨论中，你说的是图片文件尺寸，我说的是实际显示尺寸

系统剪贴板复制图片 应该是按照原始文件尺寸粘贴

**Comment by wlioi** [comment]
应该都是读取图片的实际尺寸，不过notion就给你重新排版了，把所有图片都变成一样的大小
> 系统剪贴板复制图片 应该是按照原始文件尺寸粘贴

**Comment by wlioi** [comment]
可以查看https://www.notion.so/wlioi/t-d4181f02affa4b9f9774b90b1807052b
我把印象笔记的效果对比一下

**Comment by scarsu** [comment]
插件层面无能为力

**Comment by scarsu** [comment]
新的反馈请移步： [Discussion - 意见收集](https://github.com/scarsu/NotionX/discussions/4)
