### ISSUE TITLE
Sidebar needs to be scrollable for long content

### ISSUE THREAD

**Issue by fcherman** [scarsu/NotionX#8]
My Notion pages are long and contain lots of highlighted content. I need to be able to see all of it in the NotionX sidebar, but the sidebar does not scroll. This can be easily corrected simply by adding the following CSS rule:

notionx-sidebar {
    overflow-y: scroll;
}

On a different topic, I don't understand what "Prevent Table Overflow" does, and the gif that demonstrates it moves too fast for me to see the difference. Please do a better job of explaining it, because I'm sure it's awesome. Thank you!

**Comment by scarsu** [comment]
Thank you for your feedback.

NotionX sidebar was designed to be scrollable, could you provide your platform & broswer version?

I will give a more detailed explanation of "Prevent Table Overflow" in next NotionX version, sorry for that.
